USE [master]


CREATE DATABASE [<<DBNAME>>]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PSMS', FILENAME = N'E:\SQLDATA\DATA\<<DBNAME>>.mdf' , SIZE = 6848KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'PSMS_log', FILENAME = N'E:\SQLDATA\DATA\<<DBNAME>>_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)


ALTER DATABASE [<<DBNAME>>] SET COMPATIBILITY_LEVEL = 110


IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [<<DBNAME>>].[dbo].[sp_fulltext_database] @action = 'enable'
end


ALTER DATABASE [<<DBNAME>>] SET ANSI_NULL_DEFAULT OFF 


ALTER DATABASE [<<DBNAME>>] SET ANSI_NULLS OFF 


ALTER DATABASE [<<DBNAME>>] SET ANSI_PADDING OFF 


ALTER DATABASE [<<DBNAME>>] SET ANSI_WARNINGS OFF 


ALTER DATABASE [<<DBNAME>>] SET ARITHABORT OFF 


ALTER DATABASE [<<DBNAME>>] SET AUTO_CLOSE OFF 


ALTER DATABASE [<<DBNAME>>] SET AUTO_SHRINK OFF 


ALTER DATABASE [<<DBNAME>>] SET AUTO_UPDATE_STATISTICS ON 


ALTER DATABASE [<<DBNAME>>] SET CURSOR_CLOSE_ON_COMMIT OFF 


ALTER DATABASE [<<DBNAME>>] SET CURSOR_DEFAULT  GLOBAL 


ALTER DATABASE [<<DBNAME>>] SET CONCAT_NULL_YIELDS_NULL OFF 


ALTER DATABASE [<<DBNAME>>] SET NUMERIC_ROUNDABORT OFF 


ALTER DATABASE [<<DBNAME>>] SET QUOTED_IDENTIFIER OFF 


ALTER DATABASE [<<DBNAME>>] SET RECURSIVE_TRIGGERS OFF 


ALTER DATABASE [<<DBNAME>>] SET  DISABLE_BROKER 


ALTER DATABASE [<<DBNAME>>] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 


ALTER DATABASE [<<DBNAME>>] SET DATE_CORRELATION_OPTIMIZATION OFF 




ALTER DATABASE [<<DBNAME>>] SET ALLOW_SNAPSHOT_ISOLATION OFF 


ALTER DATABASE [<<DBNAME>>] SET PARAMETERIZATION SIMPLE 


ALTER DATABASE [<<DBNAME>>] SET READ_COMMITTED_SNAPSHOT OFF 




ALTER DATABASE [<<DBNAME>>] SET RECOVERY FULL 


ALTER DATABASE [<<DBNAME>>] SET  MULTI_USER 


ALTER DATABASE [<<DBNAME>>] SET PAGE_VERIFY CHECKSUM  




ALTER DATABASE [<<DBNAME>>] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 


ALTER DATABASE [<<DBNAME>>] SET TARGET_RECOVERY_TIME = 0 SECONDS 


ALTER DATABASE [<<DBNAME>>] SET  READ_WRITE 



