USE [<<DBNAME>>]
GO
BEGIN TRAN
INSERT [dbo].[AUDIT_FUNCTION] ([FN_ID]) VALUES (N'AM0103')
GO
INSERT [dbo].[AUDIT_FUNCTION] ([FN_ID]) VALUES (N'AM0104')
GO
INSERT [dbo].[AUDIT_FUNCTION] ([FN_ID]) VALUES (N'AM0106')
GO
INSERT [dbo].[AUDIT_FUNCTION] ([FN_ID]) VALUES (N'AM0107')
GO
INSERT [dbo].[AUDIT_FUNCTION] ([FN_ID]) VALUES (N'AM03')
GO
INSERT [dbo].[AUDIT_FUNCTION] ([FN_ID]) VALUES (N'AM03R')
GO
INSERT [dbo].[AUDIT_FUNCTION] ([FN_ID]) VALUES (N'FS02')
GO
INSERT [dbo].[AUDIT_FUNCTION] ([FN_ID]) VALUES (N'FS09')
GO
INSERT [dbo].[AUDIT_FUNCTION] ([FN_ID]) VALUES (N'PA0101')
GO
INSERT [dbo].[AUDIT_FUNCTION] ([FN_ID]) VALUES (N'PA0102')
GO
INSERT [dbo].[AUDIT_FUNCTION] ([FN_ID]) VALUES (N'PA0103')
GO
INSERT [dbo].[AUDIT_FUNCTION] ([FN_ID]) VALUES (N'PA0201')
GO
INSERT [dbo].[AUDIT_FUNCTION] ([FN_ID]) VALUES (N'PA0203')
GO
INSERT [dbo].[AUDIT_FUNCTION] ([FN_ID]) VALUES (N'PA0204')
GO
INSERT [dbo].[AUDIT_FUNCTION] ([FN_ID]) VALUES (N'PA0301')
GO
INSERT [dbo].[AUDIT_FUNCTION] ([FN_ID]) VALUES (N'PA0303')
GO
INSERT [dbo].[AUDIT_FUNCTION] ([FN_ID]) VALUES (N'PA0304')
GO
INSERT [dbo].[AUDIT_FUNCTION] ([FN_ID]) VALUES (N'PA04')
GO
INSERT [dbo].[AUDIT_FUNCTION] ([FN_ID]) VALUES (N'PA11')
GO
INSERT [dbo].[AUDIT_FUNCTION] ([FN_ID]) VALUES (N'PA1201')
GO
INSERT [dbo].[AUDIT_FUNCTION] ([FN_ID]) VALUES (N'PA1202')
GO
INSERT [dbo].[AUDIT_FUNCTION] ([FN_ID]) VALUES (N'PA1203')
GO
INSERT [dbo].[AUDIT_FUNCTION] ([FN_ID]) VALUES (N'PA1204')
GO
INSERT [dbo].[AUDIT_FUNCTION] ([FN_ID]) VALUES (N'PA15')
GO
INSERT [dbo].[AUDIT_FUNCTION] ([FN_ID]) VALUES (N'PA18')
GO
INSERT [dbo].[AUDIT_FUNCTION] ([FN_ID]) VALUES (N'SA21')
GO
COMMIT TRAN