USE [<<DBNAME>>]
GO
BEGIN TRAN
INSERT [dbo].[COLOR_SETUP] ([SOLD_COLOR], [AVAIL_COLOR], [RES_COLOR], [COL_HDR_COLOR], [ROW_HDR_COLOR]) VALUES (N'FFD700', N'FFFFFF', N'FFD700', N'E0FFFF', N'FFFF00')
GO
INSERT [dbo].[COLOR_SETUP] ([SOLD_COLOR], [AVAIL_COLOR], [RES_COLOR], [COL_HDR_COLOR], [ROW_HDR_COLOR]) VALUES (N'FFD700', N'FFFFFF', N'FFD700', N'E0FFFF', N'FFFF00')
GO
INSERT [dbo].[COLOR_SETUP] ([SOLD_COLOR], [AVAIL_COLOR], [RES_COLOR], [COL_HDR_COLOR], [ROW_HDR_COLOR]) VALUES (N'FFD700', N'FFFFFF', N'FFD700', N'E0FFFF', N'FFFF00')
GO
COMMIT TRAN