USE [<<DBNAME>>]
GO
BEGIN TRAN
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0000', N'Project Name', N'6025')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0001', N'Client Identity', N'6026')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0002', N'Purchaser Type', N'1054')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0003', N'Purchase Intention', N'1198')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0004', N'Agreement Number', N'6027')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0005', N'Agreement Date', N'1013')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0006', N'Agreement Status', N'1012')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0007', N'Master Agreement Number', N'1056')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0008', N'Sales Office Name', N'454')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0009', N'Purchaser Surname', N'1159')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0010', N'Purchaser Given Name', N'1160')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0011', N'Purchaser Gender', N'6028')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0012', N'Purchaser ID', N'1011')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0013', N'Purchaser ID Type', N'6029')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0014', N'Purchaser Date Of Birth', N'6030')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0015', N'Purchaser Nationality', N'6031')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0016', N'1st Joint Buyer Surname', N'6032')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0017', N'1st Joint Buyer Given Name', N'6033')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0018', N'1st Joint Buyer Gender', N'6034')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0019', N'1st Joint Buyer ID', N'6035')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0020', N'1st Joint Buyer ID Type', N'6036')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0021', N'1st Joint Buyer Date Of Birth', N'6037')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0022', N'1st Joint Buyer Nationality', N'6038')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0023', N'2nd Joint Buyer Surname', N'6039')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0024', N'2nd Joint Buyer Given Name', N'6040')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0025', N'2nd Joint Buyer Gender', N'6041')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0026', N'2nd Joint Buyer ID', N'6042')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0027', N'2nd Joint Buyer ID Type', N'6043')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0028', N'2nd Joint Buyer Date Of Birth', N'6044')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0029', N'2nd Joint Buyer Nationality', N'6045')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0030', N'3rd Joint Buyer Surname', N'6046')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0031', N'3rd Joint Buyer Given Name', N'6047')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0032', N'3rd Joint Buyer Gender', N'6048')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0033', N'3rd Joint Buyer ID', N'6049')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0034', N'3rd Joint Buyer ID Type', N'6050')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0035', N'3rd Joint Buyer Date Of Birth', N'6051')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0036', N'3rd Joint Buyer Nationality', N'6052')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0037', N'Company Name', N'1082')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0038', N'Company BR Number', N'6053')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0039', N'1st Director Surname', N'6054')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0040', N'1st Director Given Name', N'6055')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0041', N'1st Director Gender', N'6056')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0042', N'1st Director ID', N'6057')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0043', N'1st Director ID Type', N'6058')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0044', N'1st Director Date Of Birth', N'6059')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0045', N'1st Director Nationality', N'6060')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0046', N'2nd Director Surname', N'6061')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0047', N'2nd Director Given Name', N'6062')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0048', N'2nd Director ID', N'6063')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0049', N'2nd Director ID Type', N'6064')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0050', N'Contact Person Name', N'4102')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0051', N'Contact Person Address 1', N'6065')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0052', N'Contact Person Address 2', N'6066')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0053', N'Contact Person Address 3', N'6067')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0054', N'Contact Person District', N'6068')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'00541', N'Contact Person Region', N'6069')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0055', N'Contact Person Country', N'6070')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0056', N'Contact Person Home Phone', N'6071')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0057', N'Contact Person Office Phone', N'6072')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0058', N'Contact Person Mobile Phone', N'6073')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0059', N'Contact Person Fax', N'6074')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0060', N'Contact Person Email Address', N'6075')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0061', N'Contact Person Analysis District', N'6076')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0062', N'Unit Phase', N'6077')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0063', N'Unit Block', N'6078')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0064', N'Unit Floor', N'6079')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0065', N'Unit Flat', N'6080')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'00651', N'Unit House No.', N'6081')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'00652', N'Unit Street No.', N'6082')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0066', N'Unit Street', N'6083')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0067', N'Unit GFA', N'6084')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0068', N'Unit SA', N'6085')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0069', N'Unit List Price', N'6086')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0070', N'Car Park Phase', N'6087')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'00701', N'Car Park No.', N'1050')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'00702', N'Car Park Level', N'6088')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'00703', N'Car Park House No.', N'6089')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'00704', N'Car Park Street No.', N'6090')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'00705', N'Car Park Street', N'6091')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0071', N'Car Park List Price', N'1330')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0072', N'Solicitor Firm', N'1124')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'00721', N'Solicitor Contact Person', N'6092')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0073', N'SNP Date', N'6093')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0074', N'Agency', N'1125')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0075', N'Agent Name', N'6094')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0076', N'Agent ID', N'6095')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0077', N'Agent ID Type', N'6096')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0078', N'Agent Phone', N'6097')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0079', N'Agreement Base Currency', N'6098')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0080', N'Agreement Base Currency Rate', N'6099')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0081', N'Agreement Secondary Currency', N'6100')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0082', N'Agreement Secondary Currency Rate', N'6101')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0083', N'Cash Rebate', N'6102')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0084', N'Agreement Contract Price', N'6103')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0085', N'Agreement Net Price', N'6104')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0086', N'Agreement Remarks', N'6105')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0088', N'Agreement Print Date', N'6107')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0089', N'Deed Executed', N'1234')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0090', N'Deed Execution Date', N'6108')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0091', N'Void Refund', N'6109')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0092', N'Void Remarks', N'6110')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0093', N'Created By', N'1340')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0094', N'Create Date', N'6111')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0095', N'Updated By', N'1341')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0096', N'Update Date', N'6112')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0097', N'1st Package', N'6113')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0098', N'1st Package Price', N'6114')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0099', N'1st Package Internal Cost', N'6115')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0100', N'2nd Package', N'6116')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0101', N'2nd Package Price', N'6117')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0102', N'2nd Package Internal Cost', N'6118')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0103', N'3rd Package', N'6119')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0104', N'3rd Package Price', N'6120')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0105', N'3rd Package Internal Cost', N'6121')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0106', N'4th Package', N'6122')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0107', N'4th Package Price', N'6123')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0108', N'4th Package Internal Cost', N'6124')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0109', N'5th Package', N'6125')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0110', N'5th Package Price', N'6126')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0111', N'5th Package Internal Cost', N'6127')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0112', N'Payment Method', N'1261')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'01121', N'Adjustment Percentage', N'6128')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'01122', N'Is 1st Payment Initial Payment', N'6129')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0113', N'1st Payment Desc', N'6130')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0114', N'1st Payment Amount', N'6131')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0115', N'1st Payment Before Date Desc', N'6132')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0116', N'1st Payment Due Date', N'6133')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0117', N'1st Payment After Date Desc', N'6134')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0118', N'1st Payment Currency', N'6135')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0119', N'1st Payment Currency Rate', N'6136')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0120', N'1st Payment Status', N'6137')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0121', N'2nd Payment Desc', N'6138')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0122', N'2nd Payment Due Date', N'6139')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0123', N'2nd Payment Before Date Desc', N'6140')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0124', N'2nd Payment After Date Desc', N'6141')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0125', N'2nd Payment Amount', N'6142')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0126', N'2nd Payment Currency', N'6143')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0127', N'2nd Payment Currency Rate', N'6144')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0128', N'2nd Payment Status', N'6145')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0129', N'3rd Payment Desc', N'6146')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0130', N'3rd Payment Due Date', N'6147')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0131', N'3rd Payment Before Date Desc', N'6148')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0132', N'3rd Payment After Date Desc', N'6149')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0133', N'3rd Payment Amount', N'6150')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0134', N'3rd Payment Currency', N'6151')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0135', N'3rd Payment Currency Rate', N'6152')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0136', N'3rd Payment Status', N'6153')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0137', N'4th Payment Desc', N'6154')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0138', N'4th Payment Due Date', N'6155')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0139', N'4th Payment Before Date Desc', N'6156')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0140', N'4th Payment After Date Desc', N'6157')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0141', N'4th Payment Amount', N'6158')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0142', N'4th Payment Currency', N'6159')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0143', N'4th Payment Currency Rate', N'6160')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0144', N'4th Payment Status', N'6161')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0145', N'5th Payment Desc', N'6162')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0146', N'5th Payment Due Date', N'6163')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0147', N'5th Payment Before Date Desc', N'6164')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0148', N'5th Payment After Date Desc', N'6165')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0149', N'5th Payment Amount', N'6166')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0150', N'5th Payment Currency', N'6167')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0151', N'5th Payment Currency Rate', N'6168')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0152', N'5th Payment Status', N'6169')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015201', N'6th Payment Desc', N'6501')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015202', N'6th Payment Due Date', N'6502')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015203', N'6th Payment Before Date Desc', N'6503')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015204', N'6th Payment After Date Desc', N'6504')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015205', N'6th Payment Amount', N'6505')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015206', N'6th Payment Currency', N'6506')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015207', N'6th Payment Currency Rate', N'6507')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015208', N'6th Payment Status', N'6508')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015209', N'7th Payment Desc', N'6509')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015210', N'7th Payment Due Date', N'6510')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015211', N'7th Payment Before Date Desc', N'6511')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015212', N'7th Payment After Date Desc', N'6512')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015213', N'7th Payment Amount', N'6513')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015214', N'7th Payment Currency', N'6514')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015215', N'7th Payment Currency Rate', N'6515')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015216', N'7th Payment Status', N'6516')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015217', N'8th Payment Desc', N'6517')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015218', N'8th Payment Due Date', N'6518')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015219', N'8th Payment Before Date Desc', N'6519')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015220', N'8th Payment After Date Desc', N'6520')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015221', N'8th Payment Amount', N'6521')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015222', N'8th Payment Currency', N'6522')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015223', N'8th Payment Currency Rate', N'6523')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015224', N'8th Payment Status', N'6524')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015225', N'9th Payment Desc', N'6525')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015226', N'9th Payment Due Date', N'6526')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015227', N'9th Payment Before Date Desc', N'6527')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015228', N'9th Payment After Date Desc', N'6528')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015229', N'9th Payment Amount', N'6529')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015230', N'9th Payment Currency', N'6530')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015231', N'9th Payment Currency Rate', N'6531')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015232', N'9th Payment Status', N'6532')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015233', N'10th Payment Desc', N'6533')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015234', N'10th Payment Due Date', N'6534')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015235', N'10th Payment Before Date Desc', N'6535')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015236', N'10th Payment After Date Desc', N'6536')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015237', N'10th Payment Amount', N'6537')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015238', N'10th Payment Currency', N'6538')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015239', N'10th Payment Currency Rate', N'6539')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'015240', N'10th Payment Status', N'6540')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0157', N'2nd Director Gendor', N'6242')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0158', N'2nd Director Date of Birth', N'6243')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0159', N'2nd Director Nationality', N'6244')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0160', N'Analysis Group 1', N'6202')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0161', N'Analysis Group 2', N'6203')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0162', N'Analysis Group 3', N'6216')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0163', N'Analysis Group 4', N'6217')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0164', N'Analysis Group 5', N'6218')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0165', N'Analysis Group 6', N'6219')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0166', N'Analysis Group 7', N'6220')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0167', N'Analysis Group 8', N'6221')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0168', N'Analysis Group 9', N'6222')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0169', N'Analysis Group 10', N'6223')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0170', N'Other Income', N'6548')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0171', N'Date 1', N'6549')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0172', N'Date 2', N'6550')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0173', N'Date 3', N'6551')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0174', N'Date 4', N'6552')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0175', N'Date 5', N'6553')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0176', N'Log to Register of Transaction', N'6554')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0177', N'Log to Register of Transaction Remarks', N'6555')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0178', N'Has Relationship with Vendor', N'6556')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0179', N'Average contract price per GFA', N'6557')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0180', N'Average contract price per SA', N'6558')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0181', N'Average list price per GFA', N'6559')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0182', N'Average list price per SA', N'6560')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0183', N'Average net price per GFA', N'6561')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0184', N'Average net price per SA', N'6562')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0185', N'ASP Sign date', N'6564')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AG', N'0186', N'ASP Signing Status', N'6565')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0000', N'Project Name', N'6025')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0001', N'Assignee Type', N'6174')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0002', N'Purchase Intention', N'1198')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0003', N'Agreement Number', N'6027')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0004', N'Transfer Date', N'2010')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0005', N'Transfer Number', N'6175')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0006', N'Transfer Currency', N'6176')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0007', N'Transfer Currency Rate', N'6177')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0008', N'Transfer Amount', N'2017')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0009', N'Service Charge', N'485')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0010', N'Assignee Surname', N'6178')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0011', N'Assignee Given Name', N'6179')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0012', N'Assignee Gender', N'6180')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0013', N'Assignee ID', N'6181')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0014', N'Assignee ID Type', N'6182')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0015', N'Assignee Date Of Birth', N'6183')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0016', N'Assignee Nationality', N'6184')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0017', N'1st Joint Buyer Surname', N'6032')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0018', N'1st Joint Buyer Given Name', N'6033')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0019', N'1st Joint Buyer Gender', N'6034')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0020', N'1st Joint Buyer ID', N'6035')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0021', N'1st Joint Buyer ID Type', N'6036')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0022', N'1st Joint Buyer Date Of Birth', N'6037')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0023', N'1st Joint Buyer Nationality', N'6038')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0024', N'2nd Joint Buyer Surname', N'6039')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0025', N'2nd Joint Buyer Given Name', N'6040')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0026', N'2nd Joint Buyer Gender', N'6041')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0027', N'2nd Joint Buyer ID', N'6042')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0028', N'2nd Joint Buyer ID Type', N'6043')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0029', N'2nd Joint Buyer Date Of Birth', N'6044')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0030', N'2nd Joint Buyer Nationality', N'6045')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0031', N'3rd Joint Buyer Surname', N'6046')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0032', N'3rd Joint Buyer Given Name', N'6047')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0033', N'3rd Joint Buyer Gender', N'6048')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0034', N'3rd Joint Buyer ID', N'6049')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0035', N'3rd Joint Buyer ID Type', N'6050')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0036', N'3rd Joint Buyer Date Of Birth', N'6051')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0037', N'3rd Joint Buyer Nationality', N'6052')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0038', N'Company Name', N'1082')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0039', N'Company BR Number', N'6053')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0040', N'1st Director Surname', N'6054')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0041', N'1st Director Given Name', N'6055')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0042', N'1st Director Gender', N'6056')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0043', N'1st Director ID', N'6057')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0044', N'1st Director ID Type', N'6058')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0045', N'1st Director Date Of Birth', N'6059')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0046', N'1st Director Nationality', N'6060')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0047', N'2nd Director Surname', N'6061')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0048', N'2nd Director Given Name', N'6062')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0049', N'2nd Director ID', N'6063')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0050', N'2nd Director ID Type', N'6064')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0051', N'Contact Person Name', N'4102')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0052', N'Contact Person Address 1', N'6065')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0053', N'Contact Person Address 2', N'6066')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0054', N'Contact Person Address 3', N'6067')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0055', N'Contact Person District', N'6068')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'00551', N'Contact Person Region', N'6069')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0056', N'Contact Person Country', N'6070')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0057', N'Contact Person Home Phone', N'6071')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0058', N'Contact Person Office Phone', N'6072')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0059', N'Contact Person Mobile Phone', N'6073')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0060', N'Contact Person Fax', N'6074')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0061', N'Contact Person Email Address', N'6075')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0062', N'Contact Person Analysis District', N'6076')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'AT', N'0063', N'Transfer Remarks', N'6185')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'BI', N'00009', N'Agreement No.', N'6330')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'BI', N'0001', N'Buyer/Director Name', N'6329')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'BI', N'00021', N'Buyer Type', N'6328')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'BI', N'0003', N'Contact Person', N'6310')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'BI', N'0004', N'Address 1', N'6311')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'BI', N'0005', N'Address 2', N'6312')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'BI', N'0006', N'Address 3', N'6313')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'BI', N'0007', N'Address 4', N'6314')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'BI', N'0008', N'Country', N'6315')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'BI', N'0009', N'Tel.', N'6316')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'BI', N'0010', N'Office Tel.', N'6317')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'BI', N'0011', N'Mobile', N'6318')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'BI', N'0012', N'Fax', N'6319')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'BI', N'0013', N'Email', N'6320')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'BI', N'0018', N'Unit Phase', N'6077')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'BI', N'0019', N'Unit Block', N'6078')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'BI', N'0020', N'Unit Floor', N'6079')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'BI', N'0021', N'Unit Flat', N'6080')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'BI', N'0022', N'Unit House No.', N'6081')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'BI', N'0023', N'Unit Street No.', N'6082')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'BI', N'0024', N'Unit Street', N'6083')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'BI', N'0025', N'Car Park Phase', N'6087')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'BI', N'0026', N'Car Park No.', N'1050')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'BI', N'0027', N'Car Park Level', N'6088')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'BI', N'0028', N'Car Park House No.', N'6089')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'BI', N'0029', N'Car Park Street No.', N'6090')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'BI', N'0030', N'Car Park Street', N'6091')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'BI', N'0031', N'Agreement/Transfer Date', N'6547')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0000', N'Project Name', N'6025')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0001', N'Phase', N'1026')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0002', N'Car Park No.', N'1050')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0003', N'Level', N'1051')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0004', N'House No.', N'1032')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0005', N'Street No.', N'1033')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0006', N'Street', N'1034')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0007', N'District', N'1095')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'00071', N'Region', N'877')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0008', N'Corresponding Unit Phase', N'6186')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0009', N'Corresponding Unit Block', N'6189')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0010', N'Corresponding Unit Floor', N'6190')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0011', N'Corresponding Unit Flat', N'6191')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0012', N'Corresponding Unit House No.', N'6192')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0013', N'Corresponding Unit Street No.', N'6193')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0014', N'Corresponding Unit Street', N'6194')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0015', N'Solicitor Firm', N'1124')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'00151', N'Solicitor Contact Person', N'6092')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0016', N'Sales Type', N'248')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0017', N'Add Car Park Price Before Adjustment', N'6198')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0018', N'Car Park List Price', N'1330')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0019', N'Agreement Number', N'6027')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0020', N'On Hold By (Client Identity)', N'6199')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0021', N'Car Park Status', N'6200')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0022', N'Car Park Deleted', N'6201')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0023', N'Created By', N'1340')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0024', N'Create Date', N'6111')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0025', N'Updated By', N'1341')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0026', N'Update Date', N'6112')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0027', N'Upload Date', N'314')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0028', N'Analysis Group 1', N'6202')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0029', N'Analysis Code 1', N'3311')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0030', N'Analysis Group 2', N'6203')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'CP', N'0031', N'Analysis Code 2', N'3312')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0000', N'Receipt No.', N'1564')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0001', N'Payment Type', N'9217')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0002', N'Agreement Number', N'6027')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0003', N'Project Name', N'6025')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0004', N'Unit Phase', N'6077')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0005', N'Unit Block', N'6078')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0006', N'Unit Floor', N'6079')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0007', N'Unit Flat', N'6080')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0008', N'Unit House No.', N'6081')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0009', N'Unit Street No.', N'6082')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0010', N'Unit Street', N'6083')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0011', N'Unit District', N'9218')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0012', N'Car Park Phase', N'6087')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0013', N'Car Park No.', N'275')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0014', N'Car Park Level', N'6088')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0015', N'Car Park House No.', N'6089')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0016', N'Car Park Street No.', N'6090')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0017', N'Car Park Street', N'6091')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0019', N'Payment Transaction Date', N'9219')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0020', N'Payment Status (Is Void?)', N'9220')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0021', N'Payment Method', N'1261')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0022', N'Currency', N'1306')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0023', N'Currency Rate', N'9221')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0024', N'Transaction Amount', N'1401')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0025', N'Paid Amount', N'1302')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0026', N'Credit Card Type/Cheque Bank', N'9222')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0027', N'Credit Card/Cheque No.', N'1304')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0029', N'Credit Card Expiry Date', N'9223')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0030', N'Credit Card Approval Code', N'9224')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0031', N'Settle Payment User', N'9225')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0034', N'Agreement Date', N'9226')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'DT', N'0041', N'Payment Stage', N'10000')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0000', N'Project Name', N'6025')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0001', N'Phase', N'1026')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0002', N'Block', N'1028')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0003', N'Floor', N'1030')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0004', N'Floor Sequence', N'239')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0005', N'Flat', N'1031')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0006', N'House No.', N'1032')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0007', N'Street No.', N'1033')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0008', N'Street', N'1034')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0009', N'District', N'1095')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00091', N'Region', N'877')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00101', N' Gross Floor Area (SQM)', N'')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00102', N'Net Floor Area (SQM)', N'')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00103', N'Bay Window (SQM)', N'')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00104', N'Balcony (SQM)', N'')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00105', N'Platform (SQM)', N'')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00106', N'Garden (SQM)', N'')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00107', N'Yard (SQM)', N'')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00108', N'Utility Platform (SQM)', N'')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00109', N'Air-conditioning Plant Room (SQM)', N'')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00110', N'Verandah (SQM)', N'')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00111', N'Cockloft (SQM)', N'')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00112', N'Parking (SQM)', N'')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00113', N'Roof (SQM)', N'')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00114', N'Stairhood (SQM)', N'')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00115', N'Terrace (SQM)', N'')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00116', N'Gross Floor Area (SQF)', N'')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00117', N'Net Floor Area (SQF)', N'')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00118', N'Bay Window (SQF)', N'')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00119', N'Balcony (SQF)', N'')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00120', N'Platform (SQF)', N'')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00121', N'Garden (SQF)', N'')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00122', N'Yard (SQF)', N'')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00123', N'Utility Platform (SQF)', N'')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00124', N'Air-conditioning Plant Room (SQF)', N'')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00125', N'Verandah (SQF)', N'')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00126', N'Cockloft (SQF)', N'')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00127', N'Parking (SQF)', N'')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00128', N'Roof (SQF)', N'')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00129', N'Stairhood (SQF)', N'')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00130', N'Terrace (SQF)', N'')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0021', N'Label 1', N'6213')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0022', N'Label 2', N'6214')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0023', N'Remarks', N'1243')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0024', N'Solicitor Firm', N'1124')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'00241', N'Solicitor Contact Person', N'6092')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0025', N'Sales Type', N'248')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0026', N'Unit Type', N'208')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0027', N'Unit List Price', N'6086')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0028', N'Agreement Number', N'6027')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0029', N'On Hold By (Client Identity)', N'6199')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0030', N'Unit Status', N'744')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0031', N'Unit Deleted', N'6215')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0032', N'Created By', N'1340')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0033', N'Create Date', N'6111')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0034', N'Updated By', N'1341')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0035', N'Update Date', N'6112')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0036', N'Upload Date', N'314')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0037', N'Analysis Group 1', N'6202')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0038', N'Analysis Code 1', N'3311')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0039', N'Analysis Group 2', N'6203')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0040', N'Analysis Code 2', N'3312')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0041', N'Analysis Group 3', N'6216')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0042', N'Analysis Code 3', N'3313')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0043', N'Analysis Group 4', N'6217')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0044', N'Analysis Code 4', N'3314')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0045', N'Analysis Group 5', N'6218')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0046', N'Analysis Code 5', N'3315')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0047', N'Analysis Group 6', N'6219')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0048', N'Analysis Code 6', N'3316')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0049', N'Analysis Group 7', N'6220')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0050', N'Analysis Code 7', N'3317')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0051', N'Analysis Group 8', N'6221')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0052', N'Analysis Code 8', N'3318')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0053', N'Analysis Group 9', N'6222')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0054', N'Analysis Code 9', N'3319')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0055', N'Analysis Group 10', N'6223')
GO
INSERT [dbo].[EXPORT_COLUMNS] ([TEMPLATE_TYPE], [COLUMN_CODE], [COLUMN_NAME], [COLUMN_NAME_MSG_CDE]) VALUES (N'FM', N'0056', N'Analysis Code 10', N'3320')
GO
COMMIT TRAN