USE [<<DBNAME>>]
GO
BEGIN TRAN
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'AM', N'Preliminary Agreement', N'臨時買賣合約', NULL, N'Preliminary Agreement', N'臨時買賣合約', N'SYSTEM', N'SYSTEM', N'SYTEM', CAST(N'1900-01-01T00:00:00.000' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'1900-01-01T00:00:00.000' AS DateTime), 500, N'/PSMS/images/iconsets/green/g1584.png')
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'AM_AM', N'Agreement Maintenance', N'合約管理', N'AM', N'Agreement Maintenance', N'合約管理', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T11:17:13.337' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T11:17:13.337' AS DateTime), 1, N'/PSMS/images/iconsets/white/w1481.png')
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'AM_MM', N'Mailing List Maintenance', N'郵寄名單管理', N'AM', N'Mailing List Maintenance', N'郵寄名單管理', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T11:17:13.337' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T11:17:13.337' AS DateTime), 2, N'/PSMS/images/iconsets/white/w1573.png')
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'AT', N'Agreement Transfer', N'合約轉讓', NULL, N'Agreement Transfer', N'合約轉讓', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T14:42:57.870' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T14:42:57.870' AS DateTime), 800, NULL)
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'BA', N'Balloting', N'抽籤', NULL, N'Balloting', N'抽籤', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2014-03-31T12:46:31.270' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2014-03-31T12:46:31.270' AS DateTime), 300, N'/PSMS/images/iconsets/green/g1525.png')
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'BA_IO', N'Interoperability', N'互通性', N'BA', N'Interoperability', N'互通性', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2018-02-12T16:58:29.970' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2018-02-12T16:58:29.970' AS DateTime), 3, N'/PSMS/images/iconsets/white/w822.png')
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'BA_MM', N'Master Maintenance', N'編碼管理', N'BA', N'Master Maintenance', N'編碼管理', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2018-02-12T17:03:44.730' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2018-02-12T17:03:44.730' AS DateTime), 1, N'/PSMS/images/iconsets/white/w89.png')
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'BA_RM', N'Registration Maintenance', N'抽籤申請管理', N'BA_MM', N'Registration Maintenance', N'抽籤申請管理', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2018-02-13T16:13:55.413' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2018-02-13T16:13:55.413' AS DateTime), 1, NULL)
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'FM', N'Formal Agreement', N'正式買賣合約', NULL, N'Formal Agreement', N'正式買賣合約', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2010-08-21T17:02:11.043' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2010-08-21T17:02:11.043' AS DateTime), 600, NULL)
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'FM_FAM', N'Formal Agreement Maintenance', N'正式合約管理', N'FM', N'Formal Agreement Maintenance', N'正式合約管理', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2010-08-21T17:02:11.060' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2010-08-21T17:02:11.060' AS DateTime), 1, NULL)
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'FS', N'Unit Selection', N'單位選購', NULL, N'Unit Selection', N'單位選購', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T11:17:13.320' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T11:17:13.320' AS DateTime), 400, N'/PSMS/images/iconsets/green/g1594.png')
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'FS_SH', N'Unit Selection History', N'單位選購記錄', N'FS', N'Unit Selection History', N'單位選購記錄', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T11:17:13.337' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T11:17:13.337' AS DateTime), 2, N'/PSMS/images/iconsets/white/w1674.png')
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'FS_DP', N'Unit Selection Public Display', N'單位選購公眾顯示狀況', N'FS_SH', N'Unit Selection Public Display', N'單位選購公眾顯示狀況', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2018-03-15T19:05:14.537' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2018-03-15T19:05:14.537' AS DateTime), 1, NULL)
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'FS_SM', N'Unit Selection/De-Selection', N'單位選購/取消已選購', N'FS', N'Unit Selection/De-Selection', N'單位選購/取消已選購', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T11:17:13.320' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T11:17:13.320' AS DateTime), 1, N'/PSMS/images/iconsets/white/w1217.png')
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'PA', N'Project Administration', N'項目管理模組', NULL, N'Project Administration', N'項目管理模組', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T11:17:13.320' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T11:17:13.320' AS DateTime), 200, N'/PSMS/images/iconsets/green/g1436.png')
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'PA_FM', N'Unit Maintenance', N'單位管理', N'PA', N'Unit Maintenance', N'單位管理', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T11:17:13.320' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T11:17:13.320' AS DateTime), 2, N'/PSMS/images/iconsets/white/w1422.png')
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'PA_GM', N'General Maintenance', N'共通管理', N'PA_FM', N'General Maintenance', N'共通管理', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2018-02-12T17:32:31.333' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2018-02-12T17:32:31.333' AS DateTime), 1, NULL)
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'PA_IO', N'Interoperability', N'互通性', N'PA', N'Interoperability', N'互通性', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2018-02-12T14:56:27.437' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2018-02-12T14:56:27.437' AS DateTime), 3, N'/PSMS/images/iconsets/white/w822.png')
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'PA_MM', N'Master Maintenance', N'編碼管理', N'PA', N'Master Maintenance', N'編碼管理', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T11:17:13.320' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T11:17:13.320' AS DateTime), 1, N'/PSMS/images/iconsets/white/w89.png')
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'PA_PL', N'Price List Maintenance', N'價格管理', N'PA_FM', N'Price List Maintenance', N'價格管理', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2018-02-12T17:45:44.987' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2018-02-12T17:45:44.987' AS DateTime), 4, NULL)
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'PA_PM', N'Project Master Maintenance', N'銷售項目管理', N'PA_MM', N'Project Master Maintenance', N'銷售項目管理', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T12:20:23.613' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T12:20:23.613' AS DateTime), 1, NULL)
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'PA_PY', N'Payment Method Setup', N'付款方法管理', N'PA_MM', N'Payment Method Setup', N'付款方法管理', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T12:20:23.613' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T12:20:23.613' AS DateTime), 2, NULL)
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'PA_UM', N'Unit Maintenance', N'單位管理', N'PA_FM', N'Unit Maintenance', N'單位管理', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T12:24:00.383' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T12:24:00.383' AS DateTime), 1, NULL)
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'PF', N'Payment Follow-up', N'付款跟進', NULL, N'Payment Follow-up', N'付款跟進', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T11:16:39.600' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T11:16:39.600' AS DateTime), 700, N'/PSMS/images/iconsets/green/g1588.png')
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'PF_FA', N'Follow Up Action', N'跟進行動', N'PF', N'Follow Up Action', N'跟進行動', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2018-02-13T09:58:33.187' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2018-02-13T09:58:33.187' AS DateTime), 1, N'/PSMS/images/iconsets/white/w1345.png')
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'PSMS', N'PSMS', N'物業銷售管理系統', NULL, N'PSMS', N'物業銷售管理系統', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T00:00:00.000' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T00:00:00.000' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'RP', N'Reports', N'報表', NULL, N'Reports', N'報表', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T14:27:02.967' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T14:27:02.967' AS DateTime), 900, N'/PSMS/images/iconsets/green/g869.png')
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'RP_SR', N'Sales Related', N'銷售相關', N'RP', N'Sales Related', N'銷售相關', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2018-02-13T09:14:20.960' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2018-02-13T09:14:20.960' AS DateTime), 1, N'/PSMS/images/iconsets/white/w291.png')
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'SA', N'System Administration', N'系統管理模組', NULL, N'System Administration', N'系統管理模組', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'1900-01-01T00:00:00.000' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'1900-01-01T00:00:00.000' AS DateTime), 100, N'/PSMS/images/iconsets/green/g1262.png')
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'SA_MM', N'Master Maintenance', N'編碼管理', N'SA', N'Master Maintenance', N'編碼管理', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T11:17:13.320' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T11:17:13.320' AS DateTime), 2, N'/PSMS/images/iconsets/white/w89.png')
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'SA_RD', N'Region and District Maintenance', N'區域與地區編碼管理', N'SA_MM', N'Region and District Maintenance', N'區域與地區編碼管理', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2007-02-28T14:34:59.253' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2007-02-28T14:34:59.253' AS DateTime), 4, NULL)
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'SA_AG', N'Analysis Category Maintenance', N'分析種類編碼管理', N'SA_MM', N'Analysis Category Maintenance', N'分析種類編碼管理', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T14:51:27.653' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T14:51:27.653' AS DateTime), 1, NULL)
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'SA_LM', N'Solicitor Maintenance', N'律師編碼管理', N'SA_MM', N'Solicitor Maintenance', N'律師編碼管理', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2006-03-23T00:00:00.000' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2006-03-23T00:00:00.000' AS DateTime), 3, NULL)
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'SA_SD', N'Stamp Duty Maintenance', N'印花稅管理', N'SA_MM', N'Stamp Duty Maintenance', N'印花稅管理', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2007-02-09T14:31:33.327' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2007-02-09T14:31:33.327' AS DateTime), 2, NULL)
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'SA_SS', N'System Security', N'系統安全管理', N'SA', N'System Security', N'系統安全管理', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T11:17:13.320' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T11:17:13.320' AS DateTime), 3, N'/PSMS/images/iconsets/white/w704.png')
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'SA_SM', N'Special User Access Maintenance', N'特別用戶層級管理', N'SA_SS', N'Special User Access Maintenance', N'特別用戶層級管理', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T14:45:54.487' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T14:45:54.487' AS DateTime), 2, NULL)
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'SA_SO', N'Sales Maintenance', N'銷售相關管理', N'SA', N'Sales Maintenance', N'銷售相關管理', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2018-02-12T14:24:18.153' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2018-02-12T14:24:18.153' AS DateTime), 2, N'/PSMS/images/iconsets/white/w608.png')
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'SA_UM', N'User Profile Maintenance', N'用戶管理', N'SA_SS', N'User Profile Maintenance', N'用戶管理', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T14:42:57.870' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2006-03-17T14:42:57.870' AS DateTime), 1, NULL)
GO
INSERT [dbo].[FUNCTION_GROUP] ([FunctionGroupID], [FunctionGroupEngName], [FunctionGroupChiName], [ParentGroupID], [MenuEngName], [MenuChiName], [UpdateServerName], [UpdateFunctionID], [UpdateUser], [UpdateDate], [CreateFunctionID], [CreateUser], [CreateDate], [MenuOrder], [DEFAULT_ICON]) VALUES (N'SU', N'Survey', N'顧客調查', NULL, N'Survey', N'顧客調查', N'SYSTEM', N'SYSTEM', N'SYSTEM', CAST(N'2015-09-10T11:30:02.663' AS DateTime), N'SYSTEM', N'SYSTEM', CAST(N'2015-09-10T11:30:02.663' AS DateTime), 1000, NULL)
GO
COMMIT TRAN