USE [<<DBNAME>>]
GO
BEGIN TRAN
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AGENCY', N'D', N'TG_AUD_AGENCY', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AGENCY', N'I', N'TG_AUD_AGENCY', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AGENCY', N'U', N'TG_AUD_AGENCY', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_BASE', N'U', N'TG_AUD_AM_BASE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_BASE', N'I', N'TG_AUD_AM_BASE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_BASE', N'D', N'TG_AUD_AM_BASE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_BUYER', N'D', N'TG_AUD_AM_BUYER', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_BUYER', N'I', N'TG_AUD_AM_BUYER', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_BUYER', N'U', N'TG_AUD_AM_BUYER', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_CONTACT', N'U', N'TG_AUD_AM_CONTACT', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_CONTACT', N'I', N'TG_AUD_AM_CONTACT', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_CONTACT', N'D', N'TG_AUD_AM_CONTACT', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_ITEM', N'D', N'TG_AUD_AM_ITEM', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_ITEM', N'I', N'TG_AUD_AM_ITEM', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_ITEM', N'U', N'TG_AUD_AM_ITEM', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_NO_RANGE', N'U', N'TG_AUD_AM_NO_RANGE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_NO_RANGE', N'I', N'TG_AUD_AM_NO_RANGE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_NO_RANGE', N'D', N'TG_AUD_AM_NO_RANGE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_PACKAGES', N'D', N'TG_AUD_AM_PACKAGES', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_PACKAGES', N'I', N'TG_AUD_AM_PACKAGES', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_PACKAGES', N'U', N'TG_AUD_AM_PACKAGES', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_PAYMENT', N'U', N'TG_AUD_AM_PAYMENT', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_PAYMENT', N'I', N'TG_AUD_AM_PAYMENT', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_PAYMENT', N'D', N'TG_AUD_AM_PAYMENT', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_PAYMENT_FU_MORTGAGE', N'D', N'TG_AUD_AM_PAYMENT_FU_MORTGAGE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_PAYMENT_FU_MORTGAGE', N'I', N'TG_AUD_AM_PAYMENT_FU_MORTGAGE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_PAYMENT_FU_MORTGAGE', N'U', N'TG_AUD_AM_PAYMENT_FU_MORTGAGE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_PAYMENT_FU_OVERDUE_PENALTY', N'U', N'TG_AUD_AM_PAYMENT_FU_OVERDUE_PENALTY', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_PAYMENT_FU_OVERDUE_PENALTY', N'I', N'TG_AUD_AM_PAYMENT_FU_OVERDUE_PENALTY', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_PAYMENT_FU_OVERDUE_PENALTY', N'D', N'TG_AUD_AM_PAYMENT_FU_OVERDUE_PENALTY', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_PAYMENT_FU_TRANS', N'D', N'TG_AUD_AM_PAYMENT_FU_TRANS', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_PAYMENT_FU_TRANS', N'I', N'TG_AUD_AM_PAYMENT_FU_TRANS', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_PAYMENT_FU_TRANS', N'U', N'TG_AUD_AM_PAYMENT_FU_TRANS', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_PAYMENT_PLAN', N'I', N'TG_AUD_AM_PAYMENT_PLAN', N'Y')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_PAYMENT_PLAN', N'U', N'TG_AUD_AM_PAYMENT_PLAN', N'Y')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_PAYMENT_PLAN', N'D', N'TG_AUD_AM_PAYMENT_PLAN', N'Y')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_PRINT_LOG', N'D', N'TG_AUD_AM_PRINT_LOG', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_PRINT_LOG', N'U', N'TG_AUD_AM_PRINT_LOG', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AM_PRINT_LOG', N'I', N'TG_AUD_AM_PRINT_LOG', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'ANALYSIS_CODE', N'I', N'TG_AUD_ANALYSIS_CODE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'ANALYSIS_CODE', N'U', N'TG_AUD_ANALYSIS_CODE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'ANALYSIS_CODE', N'D', N'TG_AUD_ANALYSIS_CODE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'ANALYSIS_DISTRICT', N'D', N'TG_AUD_ANALYSIS_DISTRICT', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'ANALYSIS_DISTRICT', N'I', N'TG_AUD_ANALYSIS_DISTRICT', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'ANALYSIS_DISTRICT', N'U', N'TG_AUD_ANALYSIS_DISTRICT', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'ANALYSIS_GROUP', N'U', N'TG_AUD_ANALYSIS_GROUP', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'ANALYSIS_GROUP', N'I', N'TG_AUD_ANALYSIS_GROUP', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'ANALYSIS_GROUP', N'D', N'TG_AUD_ANALYSIS_GROUP', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AUDIT_FUNCTION', N'D', N'TG_AUD_AUDIT_FUNCTION', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AUDIT_FUNCTION', N'I', N'TG_AUD_AUDIT_FUNCTION', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AUDIT_FUNCTION', N'U', N'TG_AUD_AUDIT_FUNCTION', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AUDIT_LOG', N'U', N'TG_AUD_AUDIT_LOG', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AUDIT_LOG', N'I', N'TG_AUD_AUDIT_LOG', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'AUDIT_LOG', N'D', N'TG_AUD_AUDIT_LOG', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'BALLOT_BATCH', N'D', N'TG_AUD_BALLOT_BATCH', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'BALLOT_BATCH', N'I', N'TG_AUD_BALLOT_BATCH', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'BALLOT_BATCH', N'U', N'TG_AUD_BALLOT_BATCH', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'BALLOT_POOL', N'U', N'TG_AUD_BALLOT_POOL', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'BALLOT_POOL', N'D', N'TG_AUD_BALLOT_POOL', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'BALLOT_POOL', N'I', N'TG_AUD_BALLOT_POOL', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'BALLOT_POOL_REG', N'I', N'TG_AUD_BALLOT_POOL_REG', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'BALLOT_POOL_REG', N'D', N'TG_AUD_BALLOT_POOL_REG', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'BALLOT_POOL_REG', N'U', N'TG_AUD_BALLOT_POOL_REG', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'BALLOT_REG', N'U', N'TG_AUD_BALLOT_REG', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'BALLOT_REG', N'D', N'TG_AUD_BALLOT_REG', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'BALLOT_REG', N'I', N'TG_AUD_BALLOT_REG', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'BALLOT_REG_BUYER', N'D', N'TG_AUD_BALLOT_REG_BUYER', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'BALLOT_REG_BUYER', N'I', N'TG_AUD_BALLOT_REG_BUYER', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'BALLOT_REG_BUYER', N'U', N'TG_AUD_BALLOT_REG_BUYER', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'BALLOT_REG_PAY', N'U', N'TG_AUD_BALLOT_REG_PAY', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'BALLOT_REG_PAY', N'I', N'TG_AUD_BALLOT_REG_PAY', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'BALLOT_REG_PAY', N'D', N'TG_AUD_BALLOT_REG_PAY', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'BANK', N'I', N'TG_AUD_BANK', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'BANK', N'D', N'TG_AUD_BANK', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'BANK', N'U', N'TG_AUD_BANK', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'BLOCK', N'I', N'TG_AUD_BLOCK', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'BLOCK', N'U', N'TG_AUD_BLOCK', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'BLOCK', N'D', N'TG_AUD_BLOCK', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'CAR_PARK', N'I', N'TG_AUD_CAR_PARK', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'CAR_PARK', N'D', N'TG_AUD_CAR_PARK', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'CAR_PARK', N'U', N'TG_AUD_CAR_PARK', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'CAR_PARK_LEVEL', N'I', N'TG_AUD_CAR_PARK_LEVEL', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'CAR_PARK_LEVEL', N'U', N'TG_AUD_CAR_PARK_LEVEL', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'CAR_PARK_LEVEL', N'D', N'TG_AUD_CAR_PARK_LEVEL', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'CAR_PARK_SELECTION', N'I', N'TG_AUD_CAR_PARK_SELECTION', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'CAR_PARK_SELECTION', N'D', N'TG_AUD_CAR_PARK_SELECTION', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'CAR_PARK_SELECTION', N'U', N'TG_AUD_CAR_PARK_SELECTION', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'CHECK_RULE', N'I', N'TG_AUD_CHECK_RULE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'CHECK_RULE', N'U', N'TG_AUD_CHECK_RULE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'CHECK_RULE', N'D', N'TG_AUD_CHECK_RULE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'COLOR_MAP', N'I', N'TG_AUD_COLOR_MAP', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'COLOR_MAP', N'D', N'TG_AUD_COLOR_MAP', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'COLOR_MAP', N'U', N'TG_AUD_COLOR_MAP', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'COLOR_SETUP', N'U', N'TG_AUD_COLOR_SETUP', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'COLOR_SETUP', N'D', N'TG_AUD_COLOR_SETUP', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'COLOR_SETUP', N'I', N'TG_AUD_COLOR_SETUP', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'COLUMN_CHECK', N'D', N'TG_AUD_COLUMN_CHECK', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'COLUMN_CHECK', N'I', N'TG_AUD_COLUMN_CHECK', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'COLUMN_CHECK', N'U', N'TG_AUD_COLUMN_CHECK', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'COUNTRY', N'U', N'TG_AUD_COUNTRY', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'COUNTRY', N'D', N'TG_AUD_COUNTRY', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'COUNTRY', N'I', N'TG_AUD_COUNTRY', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'CREDIT_CARD_TYPE', N'I', N'TG_AUD_CREDIT_CARD_TYPE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'CREDIT_CARD_TYPE', N'D', N'TG_AUD_CREDIT_CARD_TYPE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'CREDIT_CARD_TYPE', N'U', N'TG_AUD_CREDIT_CARD_TYPE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'CURRENCY', N'U', N'TG_AUD_CURRENCY', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'CURRENCY', N'D', N'TG_AUD_CURRENCY', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'CURRENCY', N'I', N'TG_AUD_CURRENCY', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'DEVELOPMENT', N'I', N'TG_AUD_DEVELOPMENT', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'DEVELOPMENT', N'D', N'TG_AUD_DEVELOPMENT', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'DEVELOPMENT', N'U', N'TG_AUD_DEVELOPMENT', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'DISTRICT', N'U', N'TG_AUD_DISTRICT', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'DISTRICT', N'D', N'TG_AUD_DISTRICT', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'DISTRICT', N'I', N'TG_AUD_DISTRICT', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'EXPORT_COLUMNS', N'I', N'TG_AUD_EXPORT_COLUMNS', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'EXPORT_COLUMNS', N'D', N'TG_AUD_EXPORT_COLUMNS', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'EXPORT_COLUMNS', N'U', N'TG_AUD_EXPORT_COLUMNS', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'EXPORT_TEMPLATE', N'U', N'TG_AUD_EXPORT_TEMPLATE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'EXPORT_TEMPLATE', N'D', N'TG_AUD_EXPORT_TEMPLATE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'EXPORT_TEMPLATE', N'I', N'TG_AUD_EXPORT_TEMPLATE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'EXPORT_TEMPLATE_COLUMNS', N'I', N'TG_AUD_EXPORT_TEMPLATE_COLUMNS', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'EXPORT_TEMPLATE_COLUMNS', N'D', N'TG_AUD_EXPORT_TEMPLATE_COLUMNS', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'EXPORT_TEMPLATE_COLUMNS', N'U', N'TG_AUD_EXPORT_TEMPLATE_COLUMNS', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'FLAT_MASTER', N'U', N'TG_AUD_FLAT_MASTER', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'FLAT_MASTER', N'I', N'TG_AUD_FLAT_MASTER', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'FLAT_MASTER', N'D', N'TG_AUD_FLAT_MASTER', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'FLAT_PACKAGE', N'D', N'TG_AUD_FLAT_PACKAGE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'FLAT_PACKAGE', N'I', N'TG_AUD_FLAT_PACKAGE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'FLAT_PACKAGE', N'U', N'TG_AUD_FLAT_PACKAGE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'FLAT_PRICE_AUDIT', N'U', N'TG_AUD_FLAT_PRICE_AUDIT', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'FLAT_PRICE_AUDIT', N'I', N'TG_AUD_FLAT_PRICE_AUDIT', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'FLAT_PRICE_AUDIT', N'D', N'TG_AUD_FLAT_PRICE_AUDIT', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'FLAT_SELECTION', N'D', N'TG_AUD_FLAT_SELECTION', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'FLAT_SELECTION', N'I', N'TG_AUD_FLAT_SELECTION', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'FLAT_SELECTION', N'U', N'TG_AUD_FLAT_SELECTION', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'FLAT_TYPE', N'U', N'TG_AUD_FLAT_TYPE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'FLAT_TYPE', N'I', N'TG_AUD_FLAT_TYPE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'FLAT_TYPE', N'D', N'TG_AUD_FLAT_TYPE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'FM_CP_ANALYSIS_CODE', N'D', N'TG_AUD_FM_CP_ANALYSIS_CODE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'FM_CP_ANALYSIS_CODE', N'I', N'TG_AUD_FM_CP_ANALYSIS_CODE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'FM_CP_ANALYSIS_CODE', N'U', N'TG_AUD_FM_CP_ANALYSIS_CODE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'FM_CP_PAYMENT_METHOD_PRICE', N'U', N'TG_AUD_FM_CP_PAYMENT_METHOD_PRICE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'FM_CP_PAYMENT_METHOD_PRICE', N'D', N'TG_AUD_FM_CP_PAYMENT_METHOD_PRICE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'FM_CP_PAYMENT_METHOD_PRICE', N'I', N'TG_AUD_FM_CP_PAYMENT_METHOD_PRICE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'FUNCTION_GROUP', N'I', N'TG_AUD_FUNCTION_GROUP', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'FUNCTION_GROUP', N'D', N'TG_AUD_FUNCTION_GROUP', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'FUNCTION_GROUP', N'U', N'TG_AUD_FUNCTION_GROUP', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'FUNCTION_PROFILE', N'I', N'TG_AUD_FUNCTION_PROFILE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'FUNCTION_PROFILE', N'U', N'TG_AUD_FUNCTION_PROFILE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'FUNCTION_PROFILE', N'D', N'TG_AUD_FUNCTION_PROFILE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'LAW_FIRMS', N'D', N'TG_AUD_LAW_FIRMS', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'LAW_FIRMS', N'I', N'TG_AUD_LAW_FIRMS', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'LAW_FIRMS', N'U', N'TG_AUD_LAW_FIRMS', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'LAW_FIRMS_CONTACT', N'U', N'TG_AUD_LAW_FIRMS_CONTACT', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'LAW_FIRMS_CONTACT', N'I', N'TG_AUD_LAW_FIRMS_CONTACT', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'LAW_FIRMS_CONTACT', N'D', N'TG_AUD_LAW_FIRMS_CONTACT', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'LOG_CHECK', N'D', N'TG_AUD_LOG_CHECK', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'LOG_CHECK', N'I', N'TG_AUD_LOG_CHECK', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'LOG_CHECK', N'U', N'TG_AUD_LOG_CHECK', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'MAILING_LIST', N'I', N'TG_AUD_MAILING_LIST', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'MAILING_LIST', N'U', N'TG_AUD_MAILING_LIST', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'MAILING_LIST', N'D', N'TG_AUD_MAILING_LIST', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'MESSAGE', N'I', N'TG_AUD_MESSAGE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'MESSAGE', N'D', N'TG_AUD_MESSAGE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'MESSAGE', N'U', N'TG_AUD_MESSAGE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'NATIONALITY', N'U', N'TG_AUD_NATIONALITY', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'NATIONALITY', N'D', N'TG_AUD_NATIONALITY', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'NATIONALITY', N'I', N'TG_AUD_NATIONALITY', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'PACKAGES', N'D', N'TG_AUD_PACKAGES', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'PACKAGES', N'I', N'TG_AUD_PACKAGES', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'PACKAGES', N'U', N'TG_AUD_PACKAGES', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'PACKAGES_DESC', N'U', N'TG_AUD_PACKAGES_DESC', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'PACKAGES_DESC', N'D', N'TG_AUD_PACKAGES_DESC', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'PACKAGES_DESC', N'I', N'TG_AUD_PACKAGES_DESC', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'PRJ_PAY_METHOD', N'I', N'TG_AUD_PRJ_PAY_METHOD', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'PRJ_PAY_METHOD', N'D', N'TG_AUD_PRJ_PAY_METHOD', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'PRJ_PAY_METHOD', N'U', N'TG_AUD_PRJ_PAY_METHOD', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'PROJECT_ACCESS', N'U', N'TG_AUD_PROJECT_ACCESS', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'PROJECT_ACCESS', N'D', N'TG_AUD_PROJECT_ACCESS', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'PROJECT_ACCESS', N'I', N'TG_AUD_PROJECT_ACCESS', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'PROJECT_MASTER', N'I', N'TG_AUD_PROJECT_MASTER', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'PROJECT_MASTER', N'D', N'TG_AUD_PROJECT_MASTER', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'PROJECT_MASTER', N'U', N'TG_AUD_PROJECT_MASTER', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'PURCHASER_TYPE', N'I', N'TG_AUD_PURCHASER_TYPE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'PURCHASER_TYPE', N'U', N'TG_AUD_PURCHASER_TYPE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'PURCHASER_TYPE', N'D', N'TG_AUD_PURCHASER_TYPE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'PY_PLAN_DTL', N'I', N'TG_AUD_PY_PLAN_DTL', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'PY_PLAN_DTL', N'D', N'TG_AUD_PY_PLAN_DTL', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'PY_PLAN_DTL', N'U', N'TG_AUD_PY_PLAN_DTL', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'RECEIPT', N'U', N'TG_AUD_RECEIPT', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'RECEIPT', N'D', N'TG_AUD_RECEIPT', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'RECEIPT', N'I', N'TG_AUD_RECEIPT', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'REGION', N'I', N'TG_AUD_REGION', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'REGION', N'D', N'TG_AUD_REGION', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'REGION', N'U', N'TG_AUD_REGION', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SALES_OFFICE', N'U', N'TG_AUD_SALES_OFFICE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SALES_OFFICE', N'D', N'TG_AUD_SALES_OFFICE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SALES_OFFICE', N'I', N'TG_AUD_SALES_OFFICE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SALES_TYPE', N'I', N'TG_AUD_SALES_TYPE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SALES_TYPE', N'D', N'TG_AUD_SALES_TYPE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SALES_TYPE', N'U', N'TG_AUD_SALES_TYPE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SKIP_DATE', N'I', N'TG_AUD_SKIP_DATE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SKIP_DATE', N'U', N'TG_AUD_SKIP_DATE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SKIP_DATE', N'D', N'TG_AUD_SKIP_DATE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SPECIAL_ACCESS', N'D', N'TG_AUD_SPECIAL_ACCESS', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SPECIAL_ACCESS', N'U', N'TG_AUD_SPECIAL_ACCESS', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SPECIAL_ACCESS', N'I', N'TG_AUD_SPECIAL_ACCESS', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'STAMP_DUTY', N'U', N'TG_AUD_STAMP_DUTY', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'STAMP_DUTY', N'D', N'TG_AUD_STAMP_DUTY', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'STAMP_DUTY', N'I', N'TG_AUD_STAMP_DUTY', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'STAMP_DUTY_RANGE', N'I', N'TG_AUD_STAMP_DUTY_RANGE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'STAMP_DUTY_RANGE', N'D', N'TG_AUD_STAMP_DUTY_RANGE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'STAMP_DUTY_RANGE', N'U', N'TG_AUD_STAMP_DUTY_RANGE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'STREET', N'U', N'TG_AUD_STREET', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'STREET', N'I', N'TG_AUD_STREET', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'STREET', N'D', N'TG_AUD_STREET', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SURVEY', N'D', N'TG_AUD_SURVEY', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SURVEY', N'I', N'TG_AUD_SURVEY', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SURVEY', N'U', N'TG_AUD_SURVEY', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SURVEY_DETAIL', N'U', N'TG_AUD_SURVEY_DETAIL', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SURVEY_DETAIL', N'I', N'TG_AUD_SURVEY_DETAIL', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SURVEY_DETAIL', N'D', N'TG_AUD_SURVEY_DETAIL', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SURVEY_DETAIL_OPTION', N'D', N'TG_AUD_SURVEY_DETAIL_OPTION', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SURVEY_DETAIL_OPTION', N'I', N'TG_AUD_SURVEY_DETAIL_OPTION', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SURVEY_DETAIL_OPTION', N'U', N'TG_AUD_SURVEY_DETAIL_OPTION', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SURVEY_RESULT', N'U', N'TG_AUD_SURVEY_RESULT', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SURVEY_RESULT', N'I', N'TG_AUD_SURVEY_RESULT', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SURVEY_RESULT', N'D', N'TG_AUD_SURVEY_RESULT', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SURVEY_RESULT_DETAIL', N'D', N'TG_AUD_SURVEY_RESULT_DETAIL', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SURVEY_RESULT_DETAIL', N'U', N'TG_AUD_SURVEY_RESULT_DETAIL', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SURVEY_RESULT_DETAIL', N'I', N'TG_AUD_SURVEY_RESULT_DETAIL', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SYSTEM_SETUP', N'U', N'TG_AUD_SYSTEM_SETUP', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SYSTEM_SETUP', N'D', N'TG_AUD_SYSTEM_SETUP', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SYSTEM_SETUP', N'I', N'TG_AUD_SYSTEM_SETUP', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SYSTEM_SETUP_DTL', N'I', N'TG_AUD_SYSTEM_SETUP_DTL', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SYSTEM_SETUP_DTL', N'D', N'TG_AUD_SYSTEM_SETUP_DTL', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SYSTEM_SETUP_DTL', N'U', N'TG_AUD_SYSTEM_SETUP_DTL', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'UOM', N'U', N'TG_AUD_UOM', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'UOM', N'D', N'TG_AUD_UOM', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'UOM', N'I', N'TG_AUD_UOM', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'USER_PROFILE', N'I', N'TG_AUD_USER_PROFILE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'USER_PROFILE', N'D', N'TG_AUD_USER_PROFILE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'USER_PROFILE', N'U', N'TG_AUD_USER_PROFILE', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SALES_BATCH', N'I', N'TG_AUD_SALES_BATCH', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SALES_BATCH', N'D', N'TG_AUD_SALES_BATCH', N'N')
GO
INSERT [dbo].[T_TRIGGER_TABLE] ([TABLE_NAME], [EVENT], [TRIGGER_NAME], [GENERATE]) VALUES (N'SALES_BATCH', N'U', N'TG_AUD_SALES_BATCH', N'N')
GO
COMMIT TRAN